# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kloudy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kloudy
  pod 'SnapKit', '~> 5.6.0'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'lottie-ios'  
  pod 'FSPagerView'
  pod 'Charts', '4.1.0'

  target 'KloudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KloudyUITests' do
    # Pods for testing
  end

end

target 'kloudyWidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kloudyWidgetExtension

end
