# Generated by Django 4.1.2 on 2022-10-19 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("today", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Main",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_weather", models.IntegerField()),
                ("current_temperature", models.FloatField()),
                ("day_max_temperature", models.FloatField()),
                ("day_min_temperature", models.FloatField()),
                (
                    "weather",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main",
                        to="apis.weather",
                    ),
                ),
            ],
        ),
    ]
