# Generated by Django 4.1.2 on 2022-10-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("umbrella_index", models.FloatField()),
                (
                    "weather",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_index",
                        to="apis.weather",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaskIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("air_quality", models.IntegerField()),
                ("flower_quality", models.IntegerField()),
                ("dust_quality", models.IntegerField()),
                (
                    "weatherIndex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mask_index",
                        to="apis.weatherindex",
                    ),
                ),
            ],
        ),
    ]
