# Generated by Django 4.1.2 on 2022-10-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0002_weatherindex_maskindex"),
    ]

    operations = [
        migrations.RenameField(
            model_name="maskindex", old_name="weatherIndex", new_name="weather_index",
        ),
    ]
